[features]
seeds = false
skip-lint = false

[programs.localnet]
cipherpay_anchor = "XeEs3gHZGdDhs3Lm1VoukrWrEnjdC3CA5VRtowN5MGz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 