[features]
seeds = false
skip-lint = false

[programs.localnet]
cipherpay_anchor = "56nPWpjBLbh1n8vvUdCYGmg3dS5zNwLW9UhCg4MMpBmN"

[idl]
out = "target/idl"

[typescript]
out = "target/types"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "anchor test"
# anchor run init
init = "npx ts-node migrations/01_init.ts"

[workspace]
members = [
  "."
]

[build]
# Optional: Include the path to your zk_verifier constants if you want them rebuilt automatically
# rustflags = ["--cfg", "zk_mode"]
