[features]
seeds = false
skip-lint = false

[programs.localnet]
cipherpay_anchor = "C2BxtBbLeazgMuYqkqu1QnAcAioiWmRYNEir7qogvMgP"

[idl]
out = "target/idl"

[typescript]
out = "target/types"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

# [scripts]
# test = "anchor test"

[workspace]
members = [
  "."
]

[build]
# Optional: Include the path to your zk_verifier constants if you want them rebuilt automatically
# rustflags = ["--cfg", "zk_mode"]
